### ISSUE TITLE
comment group API

### ISSUE THREAD

**Issue by umutafacan** [bounswe/bounswe2015group3#219]

**Comment by umutafacan** [comment]
Done @3m00ns

**Comment by tuba-topaloglu** [comment]
Groups API is still missing comments, there are only posts.
I'm on the master branch, did you commit to another one?

**Comment by umutafacan** [comment]
done

**Comment by tuba-topaloglu** [comment]
tested, works as expected, thus issue closed. In case of bugs, a new issue will be opened.
